### ISSUE TITLE
Running 'train.py'

### ISSUE THREAD

**Issue by WonsokYoo** [jhultman/PV-RCNN#15] opened 2020-03-16 09:50 UTC
I tried to run 'train.py' to train with KITTI dataset but I am stucking in following issue:

(pvrcnn) alien@alien-Alienware-Aurora-R7:~/PV-RCNN/pvrcnn$ python train.py 
Setting up a new session...
Exception in user code:
$------------------------------------------------------------$
Traceback (most recent call last):
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f81a1ee1350>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81a1ee1350>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81a1ee1350>: Failed to establish a new connection: [Errno 111] Connection refused'))
**[Errno 111] Connection refused**
Loading cached annotations: ../data/cache/train.pkl
Creating annotations: 100%|███████████████████████████████████████████████| 3712/3712 [00:01<00:00, 1878.93it/s]
Filtering points: 100%|████████████████████████████████████████████████████| 3712/3712 [00:08<00:00, 434.06it/s]
Caching annotations: ../data/cache/train.pkl
Building database: 100%|███████████████████████████████████████████████████| 3712/3712 [00:27<00:00, 133.68it/s]
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main()
  File "train.py", line 92, in main
    scheduler = build_lr_scheduler(optimizer, cfg, start_epoch, len(dataloader))
  File "train.py", line 79, in build_lr_scheduler
    epochs=cfg.TRAIN.EPOCHS, last_epoch=last_epoch)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 1170, in __init__
    super(OneCycleLR, self).__init__(optimizer, last_epoch)
  File "/home/alien/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 41, in __init__
    "in param_groups[{}] when resuming an optimizer".format(i))
**KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"**

Do you recognize any problem here?

I put the KITTI dataset at the path as follows:
    ../data/kitti/
and the name of directories in each 'training' and 'testing' are 'calib' and 'velodyne' (not 'reduced_velodyne')

**Comment by liyang0522** [comment] 2020-03-17 14:39
i have met the similar question！ANYBODY COULD HELP? THANKS!

**Comment by jhultman** [comment] 2020-03-17 15:21
Hi, thanks for your question and I'm glad you're interested in this project. A few comments:

1. This project uses [Visdom](https://github.com/facebookresearch/visdom) to plot losses. You need to start a Visdom server before running `python train.py` to enable logging during training. Do this by running the command `visdom` in a separate terminal. You can then see the real-time plots in your browser by visiting `localhost:8097`.
2. The directory `velodyne_reduced` is created if it does not exist. See [here](https://github.com/jhultman/PV-RCNN/blob/master/pvrcnn/dataset/kitti_dataset.py#L53). You should not have to worry about this.
3. Regarding `KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"`. Thanks for reporting this -- it's a bug. I will push a fix for this soon. In the meantime, you can just remove the `last_epoch` argument in the constructor to `torch.optim.lr_scheduler.OneCycleLR` [here](https://github.com/jhultman/PV-RCNN/blob/master/pvrcnn/train.py#L75).

**Comment by WonsokYoo** [comment] 2020-03-17 23:38
Thanks jhultman!

1. I didn't know about Visdom issue, maybe I can run without connection error now.
2. Thanks for the link now I understood.
3. Actually, I googled the pytorch function and I found that 'last_epoch' means the initial training point when I resumed the training process so I tried by 'last_epoch=-1' and it worked.

Yesterday, I tried to plot the point clouds and bounding boxes by using 'Open3D' library which is developed by Intel and I'm still going on..

Do you have any plans to visualize the results with 3D visualizer?

**Comment by cqsnove** [comment] 2020-03-19 13:23
Hi, I have met the same issues . Then I tried by 'last_epoch=-1' or remove 'last_epoch',but but I am stucking in following issue:
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main()
  File "train.py", line 94, in main
    scheduler, loss_fn, cfg.TRAIN.EPOCHS, start_epoch)
  File "train.py", line 60, in train_model
    for step, item in enumerate(tqdm(dataloader, desc=f'Epoch {epoch}')):
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/tqdm/std.py", line 1108, in __iter__
    for obj in iterable:
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk/home1/cqs/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/disk/home1/cqs/PV-RCNN/pvrcnn/dataset/kitti_dataset.py", line 138, in __getitem__
    self.preprocessing(item)
  File "/mnt/disk/home1/cqs/PV-RCNN/pvrcnn/dataset/kitti_dataset.py", line 157, in preprocessing
    item['points'], item['boxes'], item['class_idx'])
  File "/mnt/disk/home1/cqs/PV-RCNN/pvrcnn/dataset/augmentation.py", line 44, in __call__
    points, boxes, class_idx)
  File "/mnt/disk/home1/cqs/PV-RCNN/pvrcnn/dataset/augmentation.py", line 190, in __call__
    samples = self.draw_samples()
  File "/mnt/disk/home1/cqs/PV-RCNN/pvrcnn/dataset/augmentation.py", line 133, in draw_samples
    len(self.database[class_idx]),
KeyError: 0
Do you recognize any problem here?

Eagerly awaiting your reply.

**Comment by WonsokYoo** [comment] 2020-03-20 04:05
@cqsnove Did you download the KITTI dataset and place in right path?

**Comment by jhultman** [comment] 2020-03-27 12:33
@cqsnove The database is a plain python dictionary with keys representing class_idx. It seems maybe your `database.pkl` was not built correctly, possibly due to a file path problem. Can you check and make sure your `train.pkl` annotations were created correctly since they are used to generate database? I suggest you load these files in an interactive python session to investigate:

```
import pickle
with open ('./train.pkl', 'rb') as f:
    annotations = pickle.load(f)
```

**Comment by cqsnove** [comment] 2020-03-27 12:39
@WonsokYoo Thank you for your reply!
I downloaded the KITTI dataset and place in right path. I find that 'class_idx' in the annotation.pkl is always -1 based on the error message in the code.I think this may be the cause of the mistake.

**Comment by cqsnove** [comment] 2020-03-27 12:45
> @cqsnove The database is a plain python dictionary with keys representing class_idx. It seems maybe your database.pkl was not built correctly, possibly due to a file path problem. Can you check and make sure your train.pkl annotations were created correctly since they are used to generate database? I suggest you load these files in an interactive python session to investigate:
> import pickle
> with open ('./train.pkl', 'rb') as f:
>     annotations = pickle.load(f)

Thank you for your reply .
In annotations, the category names are all lowercase letters, and then when converted to the corresponding Numbers, the category names start with uppercase letters, so class_idx is always -1

The corresponding code is as follows:
def class_name_to_idx(self, class_name):
        CLASS_NAME_TO_IDX = {
            "Car": 0,
            "Van": 0,
            "Pedestrian": 1,
            "Person_sitting": 1,
            "Cyclist": 2,
        }
        if class_name not in CLASS_NAME_TO_IDX.keys():
            return -1
        return CLASS_NAME_TO_IDX[class_name]

**Comment by jhultman** [comment] 2020-04-02 03:25
> Yesterday, I tried to plot the point clouds and bounding boxes by using 'Open3D' library which is developed by Intel and I'm still going on..
> 
> Do you have any plans to visualize the results with 3D visualizer?

Hi, yes I will add this functionality later -- either Open3D or Mayavi.

**Comment by jhultman** [comment] 2020-04-02 03:26
> Thank you for your reply .
> In annotations, the category names are all lowercase letters, and then when converted to the corresponding Numbers, the category names start with uppercase letters, so class_idx is always -1
> 
> The corresponding code is as follows:
> def class_name_to_idx(self, class_name):
> CLASS_NAME_TO_IDX = {
> "Car": 0,
> "Van": 0,
> "Pedestrian": 1,
> "Person_sitting": 1,
> "Cyclist": 2,
> }
> if class_name not in CLASS_NAME_TO_IDX.keys():
> return -1
> return CLASS_NAME_TO_IDX[class_name]

Hi, thanks for noticing this. In the next release I will standardize all class names to be lower case to avoid any confusion.

**Closed as completed by jhultman** 2020-04-02 03:26 UTC

**Comment by liyang0522** [comment] 2020-06-02 03:29
Before i run 'python train.py' in A terminal, i run 'visdom' in another  B termianl,  it begins to train,  but  during the training , i closed the B termianl, The training continues until the 60th epoch with the connection error ,so where can i get the results?
![image](https://user-images.githubusercontent.com/20035551/83476813-410ae600-a4c4-11ea-8667-40d2de8b84f7.png)
thank you for your reply!
